name: PR Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install npm dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npx vitest run
          elif [ -f deno.json ]; then
            deno task test
          else
            echo "No tests defined"
          fi
